---

- name: Run ad-hoc commands needed by specific app
  hosts: webservers
  sudo: yes
  sudo_user: "{{application_directory}}" 
  remote_user: "{{remoteu}}"
  vars:
     - dumb: true

  vars_files:
     - env_vars/{{ env }}.yml
     - roles/web/vars/main.yml
     - ./pass_ex.yml 
     - ../pass.yml # always use last
     

  tasks: 
 
   - name:  load initial data
     django_manage:
       command: load_initial_data
       app_path: "{{ project_path }}"
       virtualenv: "{{ virtualenv_path }}"
       settings: "{{ django_settings_file }}"
     environment: django_environment

   - name: Run Django collectstatic
     django_manage:
        command: collectstatic
        app_path: "{{ project_path }}"
        virtualenv: "{{ virtualenv_path }}"
        settings: "{{ django_settings_file }}"
     environment: django_environment


   - name: replace all instances of 'wagtaildemo' in settings file with application_directory
     replace: dest="{{virtualenv_path}}/{{project_name}}/{{application_name}}/settings/production.py" regexp="wagtaildemo" replace="{{application_directory}}"  backup=yes

     tags: replace 

   - name: Restart Supervisor
     supervisorctl: name={{ application_directory }} state=restarted
     tags: sup

   - name:  update index
     django_manage:
      command: update_index
      app_path: "{{ project_path }}"
      virtualenv: "{{ virtualenv_path }}"
      settings: "{{ django_settings_file }}"
     environment: django_environment

  
